apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
spec:
  service_type: ClusterIP
  projects_storage_access_mode: ReadWriteOnce
  projects_storage_class: local-path
  projects_persistence: true
  projects_existing_claim: awx-projects-claim
  task_privileged: true
  extra_volumes: |
    - name: awx-web-debug
      emptyDir: {}
  web_extra_volume_mounts: |
    - name: awx-web-debug
      mountPath: "/var/log/tower"
  extra_settings:
    - setting: "LOGGING['handlers']['console']['level']"
      value: "'DEBUG'"
